### ISSUE TITLE
GNU Radio can't record audio from a USB sound card, but only on the Pi

### ISSUE THREAD

**Issue by M0LTE** [M0LTE/pi-transceiver#17]
With a flow graph which just samples from the default sound card, on the Pi GRC just does this:

```
pi@pi-transceiver:~/pi-transceiver/software/flow-graphs $ ./audiotest.py
gr::log :INFO: audio source - Audio source arch: alsa
gr::log :ERROR: audio_alsa_source0 - [default]: No such file or directory
Traceback (most recent call last):
  File "/home/pi/pi-transceiver/software/flow-graphs/./audiotest.py", line 69, in <module>
    main()
  File "/home/pi/pi-transceiver/software/flow-graphs/./audiotest.py", line 54, in main
    tb = top_block_cls()
  File "/home/pi/pi-transceiver/software/flow-graphs/./audiotest.py", line 36, in __init__
    self.audio_source_0 = audio.source(samp_rate, '', True)
  File "/usr/lib/python3/dist-packages/gnuradio/audio/audio_swig.py", line 119, in make
    return _audio_swig.source_make(*args, **kwargs)
RuntimeError: audio_alsa_source
```

on an Ubuntu laptop, that works fine.

```
pi@pi-transceiver:~/pi-transceiver/software/flow-graphs $ arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
hw:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Direct hardware device without any conversions
plughw:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Hardware device with all software conversions
default:CARD=Device
    USB Audio Device, USB Audio
    Default Audio Device
sysdefault:CARD=Device
    USB Audio Device, USB Audio
    Default Audio Device
front:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Front output / input
dsnoop:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Direct sample snooping device
```

**Comment by M0LTE** [comment]
This worked fine using Raspberry Pi OS (with desktop), GRC from repos, and self-built gr-limesdr plugin for GRC 3.8

i.e. the only difference is with/without desktop

I will try again from scratch on the without-desktop OS, to see if I missed something during setup. Otherwise it is likely to be some package or configuration that exists in the desktop version but not in the lite version, which would hardly be unexpected.
